Remove old interface and use Artifacts MUMPS_jll 5.4.1
JuliaSmoothOptimizers/MUMPS.jl pull request #80
Opened 2022-01-07 09:32 UTC by amontoison

2022-01-11 22:13 UTC, dpo commented
Let's not remove the old interface until everything works. That will also help keep this PR more focused.

2022-01-11 22:46 UTC, amontoison commented
> Let's not remove the old interface until everything works. That will also help keep this PR more focused.

I update the PR to not remove the old interface except `deps/build.jl`.

I added a `ci2.yml` to test MUMPS.jl with MUMPS_jll because I updated the interface such that the users can use their own installation of MUMPS if the environment variable `MUMPS_PREFIX` is defined.
All tests with `ci_yml` still use your tap dpo/mumps-jl.

2022-01-12 00:32 UTC, dpo commented
> I added a ci2.yml to test MUMPS.jl with artifact MUMPS_jll because I updated the interface such that the users can use their own installation of MUMPS if the environment variable MUMPS_PREFIX is defined.
All tests with ci.yml still use your tap dpo/mumps-jl.

Right, but it can no longer be built...

Also, why do we need to install all three oh OpenMPI, MPICH and MicrosoftMPI???

2022-01-12 11:10 UTC, amontoison commented
> > I added a ci2.yml to test MUMPS.jl with artifact MUMPS_jll because I updated the interface such that the users can use their own installation of MUMPS if the environment variable MUMPS_PREFIX is defined.
> > All tests with ci.yml still use your tap dpo/mumps-jl.
> 
> Right, but it can no longer be built...

I found a solution to keep it.
 
> Also, why do we need to install all three oh OpenMPI, MPICH and MicrosoftMPI???

OpenMPI, MPICH and MicrosoftMPI are dependencies of MPI.jl (https://github.com/JuliaParallel/MPI.jl/blob/master/Project.toml#L10-L13).
They are required for MPItrampoline_jll.

2022-01-12 18:54 UTC, dpo commented
#81 should fix the test that fails on macOS related to accuracy.

There's still a segfault with the JLL to investigate.

2022-01-12 18:57 UTC, dpo reviewed
It all looks great, many thanks! I would prefer to leave MUMPS.jl and mumps_types.jl unchanged in this PR and update MUMPS-C_API.jl instead.

2022-01-13 14:52 UTC, dpo commented
I'll try locally.

2022-01-13 14:56 UTC, dpo requested changes

2022-01-13 14:56 UTC, dpo commented on src/MUMPS.jl
> +Note, unless working with the low-level interface, we discourage setting the `JOB`
```suggestion
Note, unless working with the low-level interace, we discourage setting the `JOB`
```

2022-01-13 14:56 UTC, dpo commented on src/MUMPS.jl
> +using MPI, Libdl, LinearAlgebra, SparseArrays
```suggestion
```

2022-01-13 14:56 UTC, dpo commented on src/MUMPS.jl
> +
```suggestion
```

2022-01-13 14:56 UTC, dpo commented on src/MUMPS_C-API.jl
> -using Libdl, LinearAlgebra, SparseArrays
restore this line (we separate stdlib imports from other imports)

2022-01-13 14:56 UTC, dpo commented on src/MUMPS_C-API.jl
> -using MPI
restore this line

2022-01-14 01:36 UTC, dpo commented
ps: at least, Homebrew is also installing binaries now, which speeds up the CI (https://github.com/JuliaSmoothOptimizers/MUMPS.jl/runs/4811639965?check_suite_focus=true#step:3:59).

pps: MUMPS itself is still being compiled on Linux... not sure why.

2022-01-14 22:01 UTC, amontoison commented
> ps: at least, Homebrew is also installing binaries now, which speeds up the CI (https://github.com/JuliaSmoothOptimizers/MUMPS.jl/runs/4811639965?check_suite_focus=true#step:3:59).

Great !

> pps: MUMPS itself is still being compiled on Linux... not sure why.

MUMPS is not compiled with my `ci2.yml` (https://github.com/JuliaSmoothOptimizers/MUMPS.jl/runs/4811022469?check_suite_focus=true).
Maybe we should update the build name of `ci.yml` and `ci2.yml`.
Instead of `CI`, we could rename them `CI-Homebrew` and `CI-Artifact`.

2022-01-22 05:51 UTC, dpo commented
I can reproduce the segmentation fault locally on macOS... :-(

2022-01-27 18:33 UTC, amontoison commented
@dpo I recompiled MUMPS_jll on my computer for `x86_64-linux-gnu` and `x86_64-apple-darwin` platforms without `ParMETIS` and deployed the new MUMPS_jll (fork amontoison/MUMPS_jll.jl).
We still have the segmentation fault :(

2022-01-27 18:48 UTC, dpo commented
😞 
It's hard to debug. I tried to follow the execution with `dtrace` and saw messages that suggested ParMETIS as a potential problem. I'll look more when I find a moment.

2022-02-07 04:44 UTC, amontoison commented
The version 2.2.0 of SCALAPACK was released four days ago: http://www.netlib.org/scalapack/#_scalapack_version_2_2_0
I recompiled it with Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/4368
It could fix our issue with Mac :crossed_fingers:

2022-02-08 05:11 UTC, amontoison commented
`SCALAPACK` 2.2.0 doesn't solved our issue but I found a topic about our segfault: https://developer.apple.com/forums/thread/121887
The solution is to recompile with `-fno-stack-check` flag.

2022-02-08 06:01 UTC, dpo commented
I tried that 10 days ago, but it didn't help. Maybe I didn't recompile Scalapack with it though. I'll have to try.

2022-08-19 04:27 UTC, amontoison commented
@dpo MUMPS_jll works on Linux and Mac !!! :tada:

2022-08-19 19:46 UTC, dpo commented
Excellent, thank you! I'm going to merge this despite the failing Homebrew actions. In the next PR, I'll remove the Homebrew actions and add M1.

2022-08-19 19:46 UTC, merged

2022-08-19 19:54 UTC, amontoison commented
We can also test FreeBSD with CirrusCI :-)